name: main

on:
  schedule:
    - cron: '0 2 * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: pip install starrail
      
    - name: Run getPackage.ps1
      run: chmod +x ./package/getPackage.ps1
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: main
        publish_dir: package
